### ISSUE TITLE
ETS configuration parameters not valid

### ISSUE THREAD

**Issue by aniceking** [thelsing/knx#106]
I run the default sample program, but when using ETS configuration parameters, three parameters can not be configured correctly and keep the same value. Where is the problem?

Timeout: 0
Zykl. senden: 12
Abgleich: 0

These two can be configured correctly：
Min/Max senden: 2
Aenderung senden: 1

Serial.print("Timeout: ");
        Serial.println(knx.paramByte(0));
        Serial.print("Zykl. senden: ");
        Serial.println(knx.paramByte(1));
        Serial.print("Min/Max senden: ");
        Serial.println(knx.paramByte(2));
        Serial.print("Aenderung senden: ");
        Serial.println(knx.paramByte(3));
        Serial.print("Abgleich: ");
        Serial.println(knx.paramByte(4));

LOG：
SAVED 00 FA 00 00 00 00 00 00 00 03 11 06 00 01 04 00 01 60 00 01 00 00 00 00 00 00 01 00 00 00 34�readMemory
RESTORED 00 FA 00 00 00 00 00 00 00 03 11 06 00 01 04 00 01 60 00 01 00 00 00 00 00 00 01 00 00 00 34 00 08 01 00 00 00 48 00 04 01 00 00 00 4C 00 04 01 00 00 00 
manufacturerId, version and hardwareType matches
saverestores 2
-10
.
-26
.

restored saveRestores
tableObjs 4
-26
.
-33
.
-40
.
-4
7
.
restored Tableobjects
Timeout: 0
Zykl. senden: 12
Min/Max senden: 2
Aenderung senden: 1
Abgleich: 0
ownaddr 1106

**Comment by thelsing** [comment]
I just tested it on esp8266. Maybe this is an endianess issue? can you check with the printHex function if the Memory changed?

**Comment by thelsing** [comment]
Closing because no response after a month. Feel free to reopen if the problem persists.
