### ISSUE TITLE
Configuring via ETS

### ISSUE THREAD

**Issue by ouranos6** [thelsing/knx#12]
Hi,

First of all it seems to be really something incredible!!
I load my first custom sensor with the bme680 code on my esp8266 and add the knxprod to my ETS.

Now I would try to configure it by the ets but how can i do it?

**Comment by thelsing** [comment]
Fist you need to bring es esp8266 in your network. Just connect to the wlan of the esp ("knx-bme680" for the bme680 example) and set the correct ssid in the webpage of the esp.

Then select the network-device of your pc that can talk to the esp as knx connection in ETS. 
(You can also use any other connection that can talk to the esp. For example an IP-Router or an USB-Interface if your knx-bus is connected to IP via a IP-Router.)

Now set the esp to programming mode. This is done with a button on gpio0 (pin can be changes with knx.buttonPin  = ..). LED_BUILDIN should be on now. (The gpio for the led can also be set with knx.ledPing = ...).

Now you should be able to configure the device like any other device with ETS.
