### ISSUE TITLE
Flash memory overlap

### ISSUE THREAD

**Issue by kg9316** [thelsing/knx#124]
Hi first let me thank you for this great library! It's the most complete out there :-)

My issue is that I also have to use the flash memory for other things.
In my case it's the iotWebConf library that's used to store other settings in my device.

I use an ESP32-Wroom-32D (OLIMEX EPS32-POE) with 4MB Flash
In the iotWebConf I can configure an offset to where it should start store information in flash, this is default to 0

In memory.h I find "KNX_FLASH_SIZE 1024", does this mean that the KNX lib use memory location 0-1024 ?
Tried to set offset in iotWebConf to a number larger that 1024 but if always fails when I "Download All in ETS", this overwrites the settings that iotWebConf uses.

What's the start memory location in the KNX lib ?
I believe this can be solved if the two libraries don't overlap in Flash ? Right ??

Best regards from
Kato

**Comment by thelsing** [comment]
You have to look at the platform implementation to find out where the settings are stored. For ESP32 look at https://github.com/thelsing/knx/blob/21a05ae9b3b8b094dc08940c44481d22c2026b48/src/esp32_platform.cpp#L84
So if you make EEPROM lib from ESP32 arduino core work with iotWebConf it will work with this stack too.
