### ISSUE TITLE
Support RP2040 MCU (e.g. Raspberry Pi Pico)

### ISSUE THREAD

**Issue by nanosonde** [thelsing/knx#126]
Some sample board which use the new RP2040 MCU:

https://www.raspberrypi.org/documentation/rp2040/getting-started/

One core for the KNX stack, one core for the application.

Quote:

> Auf dem Chip befinden sich integrierte Bibliotheken zur Beschleunigung von Fließkommaberechnungen.
> 
> Um effizientes Multithreading zu ermöglichen, umfasst der Microcontroller FIFO-Speicher, die als Mailboxen zwischen den beiden Kernen fungieren. 32 hardwarebasierte Spinlocks dienen der Synchronisation zwischen Threads.
>

**Comment by SirSydom** [comment]
basic support done in https://github.com/thelsing/knx/pull/145
