### ISSUE TITLE
Node-RED knx controller can not connect *knx-demo-coupler*

### ISSUE THREAD

**Issue by Jason0416** [thelsing/knx#163]
When use Node-RED knx-controller to connect *knx-demo-coupler*, The PIO log as: "Unhandled service identifier: 205". The 205 is KnxServiceType ConnectRequest. Need something to do ?

**Comment by thelsing** [comment]
I didn't find anything about this in the knx-spec. Do you have any reference for this identifier? Routing shouldn't need any connect requests btw.

**Comment by thelsing** [comment]
No respose. Closing.
