### ISSUE TITLE
Programming download works, but not application download

### ISSUE THREAD

**Issue by ChriD** [thelsing/knx#169]
Hi,
I can programm my device with all settings and KO's and it will work. But when i try to download partially or the application (no programming mode) the device seems to "crash" at the very and and it doesn't work. The last stuff its sends via bus when downloading the application is this:

![image](https://user-images.githubusercontent.com/2505067/151616388-9d7d8349-230f-479b-b130-31ff10adf2c3.png)

or

![image](https://user-images.githubusercontent.com/2505067/151619425-cfc6c022-2dd4-4ed3-8661-c343d1d2440e.png)

The last serial output is this (eherby this messafe appeaers while programming too and it doesnt matter there):
```
got U_STATE_IND: RE
L_DATA_CON not received within expected time
```

afterwards the board needs a reset to work again. What may cause this issue?

**Comment by ChriD** [comment]
I did some further tests and the problem appears when i am adding a KO in the CreateKNXProd
Parameters work and if i only have parameters i can download the application. But if i have one KO defined, it wont work
(Full download always works)

**Comment by ChriD** [comment]
Well, i have broke it down to the settings of the "dataPointType" for a group object. I have to investigate further

**Comment by thelsing** [comment]
If you add a KO in the knxprod you have to do a full download. The number of KO and parameters determine the size of these tables. If you change those, you should changed firmware version to reinitialize the device.

**Comment by ChriD** [comment]
I initialy did not change the KO count in the knxprod, i did this only to find the problem and if it was related to the KO's

What i do is follwoing
I do a full download and afterwards (after the automatic reboot of the device) without changing anything, i do the application download. (i even do not change parameter values or KO links in the ETS). The Application download runs for a while and before the last reset, it stalls and the device hangs. 

So Full download works, and the application download directly after the full download stalls at the very end i think.
It does not stall on application downoad if i do not "add any specification of the dataPointTypes" in the application itself.
I will investigate further tomorrow.

**Comment by ChriD** [comment]
Okay. it seems that i had a bunch of "dataPointType"  methods  called on GO's that did not exist (wrong index). 
But that did only lead to problems when downloading the application via ETS. The "running app" had no issues with this
