### ISSUE TITLE
Make MAX_APDU_SIZE configureable

### ISSUE THREAD

**Issue by SirSydom** [thelsing/knx#180]
Since not all transceiver support any length of frames, the hardcoded 0xFE for PID_MAX_APDU_LENGTH should be configureable by at least a define.

**Comment by thelsing** [comment]
Is https://github.com/thelsing/knx/blob/d27f4202177a9137491cfc8f98aa559d29103c1b/src/knx/device_object.h#L36 enough for this?

**Comment by SirSydom** [comment]
sure
