### ISSUE TITLE
Is there a way to know that an upload is in action?

### ISSUE THREAD

**Issue by ChriD** [thelsing/knx#192]
Hi,

Is there a way to know that an upload from ETS is in action?
I have a problem that sometimes the system will freeze when uploading the application.
I think this is because some other loops of the applications are running.

is knx.configured() the way to go? I want to disable  the application loop while uploading

**Comment by SirSydom** [comment]
>is knx.configured() the way to go?
yes.

**Comment by ChriD** [comment]
Thx :-)

**Comment by mumpf** [comment]
Just a remark:
Application loop might not be enough, if you use interrupt handlers and access any knx data from there, you should use knx.configured() too.
Regards,
Waldemar
