### ISSUE TITLE
callbacks missing occasionally

### ISSUE THREAD

**Issue by ErikMeinders** [thelsing/knx#235]
I used this library to create a wireless device based on an ESP32 on the multicast network. This device is ping-able, transmits cyclic status information all the time and *most* of the time successfully triggers the callback functions. However, occasionally it doesn't respond to the mcast for a while (minutes) before functioning normal again. The device does not reboot in between and other features continue to function (ping, cyclic value updates). Other devices (e.g. my laptop) listening on the same wireless network / mcast address do see the package with the correct Group Address, so I assume the infrastructure is not the problem. Does this ring a bell, anyone?

**Comment by etrinh** [comment]
Looks similar to my IGMP proxy issue
https://github.com/thelsing/knx/issues/155#issuecomment-997189953
