### ISSUE TITLE
Pass through KNX-bus to Serial with H8C09 board

### ISSUE THREAD

**Issue by mrWheel** [thelsing/knx#239]
Hi,

Can I use a H8C09 board to simply pass through KNX to an ESP32-KNX device via Serial (Tx/Rx)?

Does anyone have experience with this board and/or this setup?

My ESP32 device now works via WiFi but that is not always reliable.

**Comment by msfuture** [comment]
The H8C09 has a STM32 processor on board, that is between the KNX and Serial connection. The easiest way without soldering would be to write a sketch, that echoes the KNX serial from the BCU to the Serial and the other way around. As the STM32 does not consume that much energy I think that would be okay...

**Comment by mrWheel** [comment]
Thanks!

**Comment by Ing-Dom** [comment]
why don't you use a NanoBCU ? It's smaller and less expensive ?

**Comment by mrWheel** [comment]
@Ing-Dom .. If only there was some documentation and a reseller ..

**Comment by Ing-Dom** [comment]
https://github.com/OpenKNX/OpenKNX/wiki/NanoBCU

I sell them.
https://muster.ing-dom.de/
but currently DE only, you would have to use [LogiX ](https://www.logoix.com) or a similar service.

**Comment by msfuture** [comment]
Was my first thought too. Best option in combination with ESPs and RP2040s... But I'm from Germany, so no shipping issues...
