### ISSUE TITLE
Update PlatformIO Registry Version and Example Projects

### ISSUE THREAD

**Issue by ab-tools** [thelsing/knx#260]
Hello,

great work on this KNX project which I just started to use, but I noticed that the version available on the PlatformIO Registry is already 3 years old:
https://registry.platformio.org/libraries/thelsing/knx

Is this very old version still the recommended version to use?

I also tried to compile your [knx-demo](https://github.com/thelsing/knx/tree/master/examples/knx-demo) example project with the latest version from this repository here, but this leads to many compilation errors.

It would be great to get updated examples that work with the latest library version.

Best regards and thanks a lot for your efforts
Andreas

**Comment by thelsing** [comment]
Just created new release 1.4 platform.io will probably pick it up soon.
