### ISSUE TITLE
Arduino ethernet sheild supported?.

### ISSUE THREAD

**Issue by anand-010** [thelsing/knx#263]
i am tring to implement ip interface using ethernet sheild with arduino but i've only found wifimanager example.
 is it possible to use it with any arduino ethernet sheild?.

**Comment by thelsing** [comment]
That shouldn't be too hard. You only have to create a Bau for Knx-IP:
`KnxFacade<Esp32Platform, Bau57B0> my_knx;`
and use it. The arduino platform currently lacks support for ethernet. You would have to add it. The methods 
`    virtual void setupMultiCast(uint32_t addr, uint16_t port);
    virtual void closeMultiCast();
    virtual bool sendBytesMultiCast(uint8_t* buffer, uint16_t len);
    virtual int readBytesMultiCast(uint8_t* buffer, uint16_t maxLen);`
must be implemented for that. Look at the esp platforms for examples.
