### ISSUE TITLE
Compatible with NCN5120/NCN5121

### ISSUE THREAD

**Issue by dzungpv** [thelsing/knx#297]
Do this lib compatible with NCN5120/NCN5121? I read the #2 seem it not working fine.

**Comment by betamoojw** [comment]
Yes, it is compatible with NCN5120/NCN5121 from one of my practical exercises. This library has evolved and been refined since its birth, with many excellent contributors.

**Comment by dzungpv** [comment]
> Yes, it is compatible with NCN5120/NCN5121 from one of my practical exercises. This library has evolved and been refined since its birth, with many excellent contributors.

OK, I see in OpenKNX repo they using device with an BCU module using NCN5120/5130 and this lib to make application. https://github.com/OpenKNX/OpenKNX/blob/main/accessories/MicroBCU2/doc/MicroBCU2_Schematic_V00.15.pdf
