### ISSUE TITLE
How to add thousands of callback to a single function and identify the the group object from callback parameter.

### ISSUE THREAD

**Issue by anand-010** [thelsing/knx#302]
I am trying to design a knx ir transmitter but now i can assign multiple object callbacks to a single function but i don't which object it belongs to inside the callback function.
is there a better way to do a large number of channels at same time like the ir transmitter?.
is it possible to get some id or number of group object from the callback function?.
thank you for this project.
ir1send.callback(CallBack);
ir2send.callback(CallBack);
ir3send.callback(CallBack);
void CallBack(GroupObject& go)
{
   //get group object id or number from here?.
   number = go.?
}

**Comment by thelsing** [comment]
You are probably looking for asap().
This is the application service access point (from knx spec) aka number of the communication object.

**Comment by anand-010** [comment]
Thank you i think it is the solution.
