### ISSUE TITLE
Internal sensor correction value (value * 0.1 K) not present in KNXPROD

### ISSUE THREAD

**Issue by jeff25** [thelsing/knx#37]
Hi,

the internal sensor correction value (value * 0.1 K) is not present as communication Object in the KNXPROD File. I try KNXPROD from KNX-DEMO - IP. I Try to fix but did not work :-)

Br,
RObert

**Comment by thelsing** [comment]
I don't really know what you are talking about, but if you mean the correction value of the knx-demo example,  it is accessable as a parameter value. See https://github.com/thelsing/knx/blob/3063bf8195e8491f4955e4a6e89c1533074084c1/examples/knx-demo/knx-demo.ino#L88
