### ISSUE TITLE
ESP8266 is not programmed from the ETS after the first reboot

### ISSUE THREAD

**Issue by Boolkinator** [thelsing/knx#51]

**Comment by thelsing** [comment]
This is a bug in the esp8266 arduino core. The Readme.md already mentions that you have to reset after flashing manually.

**Comment by Boolkinator** [comment]
Not. This issue has appeared recently in recent releases. The firmware goes fine, then I reboot manually. ETS goes through IP programming, then reboots and that's it - device not responding. A manual reboot at this point does not help.

**Comment by thelsing** [comment]
This should work again now.
