### ISSUE TITLE
Separate directories for different platforms

### ISSUE THREAD

**Issue by nanosonde** [thelsing/knx#6]
Hi!
I think it would be better to move the platform specific stuff to separate folders.

What do you think?

However, I am happy that you have removed the submodule stuff. :+1:

**Comment by thelsing** [comment]
There are only 2 platform specific files per platform. (Well 3 for linux). So I don't see the need to split them up. But if you submit a pull request I will merge it ;)

**Comment by nanosonde** [comment]
Ok, currently there are only those 3 platforms, but who knows. ;)

What I have in mind is something like this:
https://github.com/bluekitchen/btstack

**Comment by thelsing** [comment]
Looks fine.

**Comment by nanosonde** [comment]
I have closed the PR as I do not want to put any more effort into this for now as I am not sure if you really like the idea.

Just take it as an example of how I wanted to do it. However, I am not sure if it fits your VisualGDB development approach.

**Comment by thelsing** [comment]
You are a bit too impatient. You created the pull request 4 days ago and closed it 2 days ago. I do this for fun and have a life too. So it can take some time till I check a pull request in detail.

**Comment by nanosonde** [comment]
Sorry for the hassle. It is not related to the time frame in anyway, but more related to my activities and priorities of those. 
I have changed them spontaneously.

So again: no offense!
