### ISSUE TITLE
Version not updated in PIO

### ISSUE THREAD

**Issue by Elandril** [thelsing/knx#67]
I've noticed that PIO still shows version 1.0.0 as the current one. I think it's because library.properties file was not updated to reflect the 1.1.0 version.

Would you be so kind to update this file?

**Comment by thelsing** [comment]
I just updated the file an created a new release.

**Comment by Elandril** [comment]
Many thanks! 👍 

PIO can install it now.

PS: Also, thanks for developing and publishing this library! I'm excited to add some custom sensors to my home KNX.
