### ISSUE TITLE
Create support for knx-IP discovery to support direct ip programming

### ISSUE THREAD

**Issue by thelsing** [thelsing/knx#9]

**Comment by nanosonde** [comment]
Hi!

I am currently working on this indirectly, as I have implemented a simple cEMI Server with KNX USB data interface support. ETS and Net'n'Node recognize it already.
While implementing this, I am keeping this in mind. Once this is done, it should be rather easy to add support for this too. However, so far I have NOT implemented cEMI Translayer Mode as I hope that the normal data link layer is enough (see PID_COMM_MODE).

BTW: I have already experimented with IP discovery. Answering just the SEARCH_REQ with a proper response (only routing, no tunneling) is enough to make a generic multicast ethernet interface apear in ETS that you can select to do program a device via IP and data link layer (via an IP router).
