### ISSUE TITLE
Device not responding on last commit

### ISSUE THREAD

**Issue by ajlajlajl** [thelsing/knx#96]
Hi
I've got a project that was on this commit 
https://github.com/thelsing/knx/commit/52d3866e41e1e9fd460f366bd9016daf82ec5e12

I pulled yesterday and updated my knx stack. since then my device is not responding to requests!
or if i have to be more specific, ETS cant find module (PhysAddrRead receives no answer).
But in debug serial I get this:
```
dataBroadcastIndication
dataBroadcastRequest
dataBroadcastConfirm
```
so it seems device is receiving and answering the request (? not sure).
btw. Im using STM32 and ncn5130.

and, if i rollback to the commit Ive mentioned above, everyting works fine. Ive tested this with a new fresh project and one of samples and it had the same problem too.

btw2. it seems new version's configs is not compatible with last one so I've got to erase config and cant test a configured device.

**Comment by thelsing** [comment]
KNX-IP works now. The default routing count was wrong. I also disabled Data-Secure but this is probably unrelated.

Can you test with current head please?

**Comment by ajlajlajl** [comment]
yup, its working now.
Thanks.
