### ISSUE TITLE
"induvidual" vs individual

### ISSUE THREAD

**Issue by nrobadey** [thelsing/knx#98]
individual is spelled "induvidual" at several places in the code. Is it a typo?

See https://github.com/thelsing/knx/search?q=induvidual

**Comment by nrobadey** [comment]
The same with "frameRecieved" vs frameReceived

**Comment by nrobadey** [comment]
#Nikwest posted a pull request for this issue: https://github.com/thelsing/knx/pull/100

**Comment by thelsing** [comment]
fixed in #100.
